INSERT INTO USERS (ID, NAME)
VALUES (1, 'Alice');
INSERT INTO USERS (ID, NAME)
VALUES (2, 'Bob');
INSERT INTO USERS (ID, NAME)
VALUES (3, 'Charlie');
INSERT INTO USERS (ID, NAME)
VALUES (4, 'Diana');
INSERT INTO USERS (ID, NAME)
VALUES (5, 'Ethan');
INSERT INTO USERS (ID, NAME)
VALUES (6, 'Fiona');
INSERT INTO USERS (ID, NAME)
VALUES (7, 'George');
INSERT INTO USERS (ID, NAME)
VALUES (8, 'Hannah');
INSERT INTO USERS (ID, NAME)
VALUES (9, 'Ian');
INSERT INTO USERS (ID, NAME)
VALUES (10, 'Julia');
INSERT INTO USERS (ID, NAME)
VALUES (11, 'Kevin');
INSERT INTO USERS (ID, NAME)
VALUES (12, 'Laura');
INSERT INTO USERS (ID, NAME)
VALUES (13, 'Michael');
INSERT INTO USERS (ID, NAME)
VALUES (14, 'Nina');
INSERT INTO USERS (ID, NAME)
VALUES (15, 'Oliver');
INSERT INTO USERS (ID, NAME)
VALUES (16, 'Paula');
INSERT INTO USERS (ID, NAME)
VALUES (17, 'Quentin');
INSERT INTO USERS (ID, NAME)
VALUES (18, 'Rachel');
INSERT INTO USERS (ID, NAME)
VALUES (19, 'Steve');
INSERT INTO USERS (ID, NAME)
VALUES (20, 'Tina');
